# Generated by Django 5.1.3 on 2024-12-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isOnline',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
